# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/w5/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/w5/proprietary/etc/ACDB/Bluetooth_cal.acdb:system/etc/ACDB/Bluetooth_cal.acdb \
    vendor/lge/w5/proprietary/etc/ACDB/General_cal.acdb:system/etc/ACDB/General_cal.acdb \
    vendor/lge/w5/proprietary/etc/ACDB/Global_cal.acdb:system/etc/ACDB/Global_cal.acdb \
    vendor/lge/w5/proprietary/etc/ACDB/Handset_cal.acdb:system/etc/ACDB/Handset_cal.acdb \
    vendor/lge/w5/proprietary/etc/ACDB/Hdmi_cal.acdb:system/etc/ACDB/Hdmi_cal.acdb \
    vendor/lge/w5/proprietary/etc/ACDB/Headset_cal.acdb:system/etc/ACDB/Headset_cal.acdb \
    vendor/lge/w5/proprietary/etc/ACDB/Speaker_cal.acdb:system/etc/ACDB/Speaker_cal.acdb \
    vendor/lge/w5/proprietary/etc/ACDB/workspaceFile.qwsp:system/etc/ACDB/workspaceFile.qwsp \
    vendor/lge/w5/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/lge/w5/proprietary/vendor/firmware/keymaster.ms323/keymaster.b00:system/vendor/firmware/keymaster.ms323/keymaster.b00 \
    vendor/lge/w5/proprietary/vendor/firmware/keymaster.ms323/keymaster.b01:system/vendor/firmware/keymaster.ms323/keymaster.b01 \
    vendor/lge/w5/proprietary/vendor/firmware/keymaster.ms323/keymaster.b02:system/vendor/firmware/keymaster.ms323/keymaster.b02 \
    vendor/lge/w5/proprietary/vendor/firmware/keymaster.ms323/keymaster.b03:system/vendor/firmware/keymaster.ms323/keymaster.b03 \
    vendor/lge/w5/proprietary/vendor/firmware/keymaster.ms323/keymaster.mdt:system/vendor/firmware/keymaster.ms323/keymaster.mdt
